# -*- coding: utf-8 -*-
"""CIFAR10 Adversarial Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySQVpxqip-oP4-sdf3Ih3GB-d4UCskRZ
"""

#from google.colab import drive
#drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import numpy as np
import math
import os

device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
device

"""Arguments"""

args = {
    'train_batch_size' : 128,  # input batch size for training (default: 128)
    'test_batch_size'  : 128,  # input batch size for testing (default: 128)
    'epochs' : 2,             # number of epochs to train  
    
    'weight_decay' : 2e-4,
    'lr' : 0.1,                # learning rate
    'momentum' : 0.9,          # SGD momentum
    
    'epsilon' : 0.031,         # perturbation
    'num_steps' : 1,          # perturb number of steps
    'step_size' : 0.007,       # perturb step size

    'beta'   : 6.0,            # regularization (1/lambda) in TRADES
    'seed'   : 1,              # random seed
    'log_interval' : 100,      # how many batches to wait before logging training status

    'save_freq' : 1,           # save frequency
    'model_dir' : './CIFAR10',   # directory of model for saving checkpoint

}

kwargs = {'num_workers' : 1, 'pin_memory' : True} if device.type=='cuda' else {}

"""Fix Randomization"""

torch.manual_seed(args['seed'])

"""Setup CIFAR10 Data Loader"""

import torchvision
from torchvision import datasets, transforms

transfrom_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(), 
])

transform_test = transforms.Compose([
    transforms.ToTensor()
])

trainset = datasets.CIFAR10(root=args['model_dir'], train=True, download=True, transform=transfrom_train)
testset = datasets.CIFAR10(root=args['model_dir'], train=False, download=True, transform=transform_test)

train_loader = torch.utils.data.DataLoader(trainset, 
                                           batch_size = args['train_batch_size'],
                                           shuffle = True, **kwargs)

test_loader  = torch.utils.data.DataLoader(testset, 
                                           batch_size = args['test_batch_size'],
                                           shuffle = False, **kwargs)

"""Model"""

class BasicBlock(nn.Module):
    def __init__(self, in_planes, out_planes, stride, dropRate=0.0):
        super(BasicBlock, self).__init__()
        self.bn1 = nn.BatchNorm2d(in_planes)
        self.relu1 = nn.ReLU(inplace=True)
        self.conv1 = nn.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride,
                               padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_planes)
        self.relu2 = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(out_planes, out_planes, kernel_size=3, stride=1,
                               padding=1, bias=False)
        self.droprate = dropRate
        self.equalInOut = (in_planes == out_planes)
        self.convShortcut = (not self.equalInOut) and nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride,
                                                                padding=0, bias=False) or None

    def forward(self, x):
        if not self.equalInOut:
            x = self.relu1(self.bn1(x))
        else:
            out = self.relu1(self.bn1(x))
        out = self.relu2(self.bn2(self.conv1(out if self.equalInOut else x)))
        if self.droprate > 0:
            out = F.dropout(out, p=self.droprate, training=self.training)
        out = self.conv2(out)
        return torch.add(x if self.equalInOut else self.convShortcut(x), out)


class NetworkBlock(nn.Module):
    def __init__(self, nb_layers, in_planes, out_planes, block, stride, dropRate=0.0):
        super(NetworkBlock, self).__init__()
        self.layer = self._make_layer(block, in_planes, out_planes, nb_layers, stride, dropRate)

    def _make_layer(self, block, in_planes, out_planes, nb_layers, stride, dropRate):
        layers = []
        for i in range(int(nb_layers)):
            layers.append(block(i == 0 and in_planes or out_planes, out_planes, i == 0 and stride or 1, dropRate))
        return nn.Sequential(*layers)

    def forward(self, x):
        return self.layer(x)


class WideResNet(nn.Module):
    def __init__(self, depth=34, num_classes=10, widen_factor=10, dropRate=0.0):
        super(WideResNet, self).__init__()
        nChannels = [16, 16 * widen_factor, 32 * widen_factor, 64 * widen_factor]
        assert ((depth - 4) % 6 == 0)
        n = (depth - 4) / 6
        block = BasicBlock
        # 1st conv before any network block
        self.conv1 = nn.Conv2d(3, nChannels[0], kernel_size=3, stride=1,
                               padding=1, bias=False)
        # 1st block
        self.block1 = NetworkBlock(n, nChannels[0], nChannels[1], block, 1, dropRate)
        # 2nd block
        self.block2 = NetworkBlock(n, nChannels[1], nChannels[2], block, 2, dropRate)
        # 3rd block
        self.block3 = NetworkBlock(n, nChannels[2], nChannels[3], block, 2, dropRate)
        # global average pooling and classifier
        self.bn1 = nn.BatchNorm2d(nChannels[3])
        self.relu = nn.ReLU(inplace=True)
        self.fc = nn.Linear(nChannels[3], num_classes)
        self.nChannels = nChannels[3]

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()
            elif isinstance(m, nn.Linear):
                m.bias.data.zero_()

    def forward(self, x):
        out = self.conv1(x)
        out = self.block1(out)
        out = self.block2(out)
        out = self.block3(out)
        out = self.relu(self.bn1(out))
        out = F.avg_pool2d(out, 8)
        out = out.view(-1, self.nChannels)
        return self.fc(out)

def squared_l2_norm(x):
    flattened = x.view(x.unsqueeze(0).shape[0], -1)
    return (flattened ** 2).sum(1)


def l2_norm(x):
    return squared_l2_norm(x).sqrt()


def trades_loss(model,
                x_natural,
                y,
                optimizer,
                prev_delta,
                step_size=0.003,
                epsilon=0.031,
                perturb_steps=10,
                beta=1.0,
                distance='l_inf', 
                ):
    # define KL-loss
    criterion_kl = nn.KLDivLoss(size_average=False)
    model.eval()
    batch_size = len(x_natural)
    # generate adversarial example
    x_adv = x_natural.detach() + (torch.tile(prev_delta,(x_natural.shape[0],1,1,1))).detach()
    if distance == 'l_inf':
        #for _ in range(perturb_steps):
        x_adv.requires_grad_()
        with torch.enable_grad():
            loss_kl = criterion_kl(F.log_softmax(model(x_adv), dim=1),
                                    F.softmax(model(x_natural), dim=1))
        grad = torch.autograd.grad(loss_kl, [x_adv])[0]
        x_adv = x_adv.detach() + step_size * torch.sign(grad.detach())
        x_adv = torch.min(torch.max(x_adv, x_natural - epsilon), x_natural + epsilon)
        x_adv = torch.clamp(x_adv, 0.0, 1.0)
        new_delta = x_adv - x_natural
        new_delta = torch.sum(new_delta,axis=0)/(new_delta.shape[0]) ## taking average of perturbations
    elif distance == 'l_2':
        delta = 0.001 * torch.randn(x_natural.shape).cuda().detach()
        delta = Variable(delta.data, requires_grad=True)

        # Setup optimizers
        optimizer_delta = optim.SGD([delta], lr=epsilon / perturb_steps * 2)

        for _ in range(perturb_steps):
            adv = x_natural + delta

            # optimize
            optimizer_delta.zero_grad()
            with torch.enable_grad():
                loss = (-1) * criterion_kl(F.log_softmax(model(adv), dim=1),
                                           F.softmax(model(x_natural), dim=1))
            loss.backward()
            # renorming gradient
            grad_norms = delta.grad.view(batch_size, -1).norm(p=2, dim=1)
            delta.grad.div_(grad_norms.view(-1, 1, 1, 1))
            # avoid nan or inf if gradient is 0
            if (grad_norms == 0).any():
                delta.grad[grad_norms == 0] = torch.randn_like(delta.grad[grad_norms == 0])
            optimizer_delta.step()

            # projection
            delta.data.add_(x_natural)
            delta.data.clamp_(0, 1).sub_(x_natural)
            delta.data.renorm_(p=2, dim=0, maxnorm=epsilon)
        x_adv = Variable(x_natural + delta, requires_grad=False)
    else:
        x_adv = torch.clamp(x_adv, 0.0, 1.0)
    model.train()

    x_adv = Variable(torch.clamp(x_adv, 0.0, 1.0), requires_grad=False)
    # zero gradient
    optimizer.zero_grad()
    # calculate robust loss
    logits = model(x_natural)
    loss_natural = F.cross_entropy(logits, y)
    loss_robust = (1.0 / batch_size) * criterion_kl(F.log_softmax(model(x_adv), dim=1),
                                                    F.softmax(model(x_natural), dim=1))
    loss = loss_natural + beta * loss_robust
    return loss, new_delta

"""Pretraining the Model"""

def adjust_learning_rate(optimizer, epoch, old_lr):
    """decrease the learning rate"""
    lr = old_lr
    if epoch >= 75:
        lr = old_lr * 0.1
    if epoch >= 90:
        lr = old_lr * 0.01
    if epoch >= 100:
        lr = old_lr * 0.001

    for param_group in optimizer.param_groups:
        param_group['lr'] = lr

def train(args, model, device, data_loader, optimizer, epoch):
    model.train()
    delta = None
    for batch_idx, (data, target) in enumerate(data_loader):
        data, target = data.to(device), target.to(device)

        optimizer.zero_grad()
        if delta==None:
          delta = 0.001 * torch.randn(data.shape[1:]).cuda()
          # print(data.shape)
          # print(delta.shape)

        loss, delta = trades_loss(model=model,
                           x_natural=data,
                           y=target,
                           optimizer=optimizer,
                           prev_delta = delta,
                           step_size=args["step_size"],
                           epsilon=args["epsilon"],
                           perturb_steps=args["num_steps"],
                           beta=args["beta"],
			                     distance='l_inf'
                           )
        loss.backward()
        optimizer.step()

        # print progress
        if batch_idx % args['log_interval'] == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(data_loader.dataset),
                       100. * batch_idx / len(data_loader), loss.item()))


def evaluate(model, device, data_loader):
    model.eval()
    loss = 0
    correct = 0

    with torch.no_grad():

        for data, target in data_loader:
            data, target = data.to(device), target.to(device)

            output = model(data)
            loss += F.cross_entropy(output, target, size_average=False).item()
            pred = output.max(1, keepdim=True)[1]
            correct += pred.eq(target.view_as(pred)).sum().item()

    loss /= len(data_loader.dataset)
    accuracy = correct / len(data_loader.dataset)

    print('Evaluation: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)'.format(
        loss, correct, len(data_loader.dataset), 100.0 * accuracy))
     
    return loss, accuracy


def main(model, args):
    optimizer = optim.SGD(model.parameters(),
                          lr=args['lr'], momentum=args['momentum'],
                          weight_decay=args['weight_decay'])
    model_dir = args['model_dir']
    for epoch in range(1, args['epochs'] + 1):
        # adjust learning rate for SGD
        adjust_learning_rate(optimizer, epoch, args['lr'])

        # training
        train(args, model, device, train_loader, optimizer, epoch)

        # evaluation on natural examples
        print('================================================================')
        evaluate(model, device, train_loader)
        evaluate(model, device, test_loader)
        print('================================================================')

        # save checkpoint
        if epoch % args['save_freq'] == 0:
            torch.save(model.state_dict(),
                       os.path.join(model_dir, 'model-wideres-epoch{}.pt'.format(epoch)))
            torch.save(optimizer.state_dict(),
                       os.path.join(model_dir, 'opt-wideres-checkpoint_epoch{}.tar'.format(epoch)))

model = WideResNet().to(device)

"""Train started at 12:54 pm (You can see executioin time by clocking over cell)"""

main(model,args)

"""Attack"""

model_path = './CIFAR10/model-wideres-epoch6.pt'

model = WideResNet().to(device)
model.load_state_dict(torch.load(model_path))

def attack(model, device, test_loader, is_random_initial, args, num_steps):
    torch.manual_seed(args['seed'])  

    epsilon   = args['epsilon']
    # num_steps = args['num_steps']
    step_size = args['step_size']

    natural_err_total = 0
    robust_err_total = 0
    total_samples = 0
    model.eval()
    for batch_idx, (data, target) in enumerate(test_loader):
          data, target = data.to(device), target.to(device)
          # print(data.shape)
          # PGD attack
          X, y = Variable(data, requires_grad=True), Variable(target)

          out = model(X)
          err_natural = (out.data.max(1)[1] != y.data).float().sum()

          X_attack = Variable(X.data, requires_grad=True)
          if is_random_initial:
            random_noise = torch.FloatTensor(*X_attack.shape).uniform_(-epsilon, epsilon).to(device)
            X_attack = Variable(X_attack.data + random_noise, requires_grad=True)
          
          for _ in range(num_steps):
                opt = optim.SGD([X_attack], lr=1e-3)
                opt.zero_grad()

                with torch.enable_grad():
                  loss = nn.CrossEntropyLoss()(model(X_attack), y)
                loss.backward()

                eta = step_size * X_attack.grad.data.sign()
                X_attack = Variable(X_attack.data + eta, requires_grad=True)
                eta = torch.clamp(X_attack.data - X.data, -epsilon, epsilon)
                X_attack = Variable(X.data + eta, requires_grad=True)
                X_attack = Variable(torch.clamp(X_attack, 0, 1.0), requires_grad=True)
          
          err_robust = (model(X_attack).data.max(1)[1]!=y.data).float().sum()
          total_samples+=data.shape[0]
          natural_err_total += err_natural
          robust_err_total += err_robust
          # print progress
          print('BatchID: {}, natural_err: {:.3f}, roubust_err: {:.3f}'.format(
                    batch_idx, err_natural, err_robust))
          if batch_idx == 5:
            break
    print('natural_accuracy: {:.3f}, roubust_accuracy: {:.3f}'.format(100.0*(1-(natural_err_total/total_samples)),100.0*(1-(robust_err_total/total_samples))))
    return natural_err_total, robust_err_total

# FGSM-20
attack(model,device,test_loader,True,args,num_steps=20)

